"""Criar tabela crientes

Revision ID: 3868e66bc0b8
Revises: 4a77e7f8f9a9
Create Date: 2026-08-19 14:56:30.542639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3868e66bc0b8'
down_revision: Union[str, Sequence[str], None] = '4a77e7f8f9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
